from sqlalchemy import (
    Boolean,
    CheckConstraint,
    Column,
    ForeignKey,
    ForeignKeyConstraint,
    Index,
    Integer,
    String,
    Table,
    Text,
    UniqueConstraint,
)

from app.models.common import identity, meeting_fk, metadata, now, segment_fk, timestamps, version

chat_messages = Table(
    "chat_messages",
    metadata,
    identity(),
    Column("workspace_id", String(36), nullable=False),
    Column("meeting_id", String(36), nullable=False),
    Column("conversation_id", String(36), nullable=False),
    Column("role", String, nullable=False),
    Column("content", Text, nullable=False),
    Column("provider", String),
    Column("model", String(120)),
    Column("source_revision", Integer, nullable=False),
    Column("created_at", String, nullable=False, default=now),
    meeting_fk(),
    UniqueConstraint("workspace_id", "meeting_id", "id"),
    CheckConstraint("role IN ('user','assistant')", name="role"),
    Index("ix_chat_chronological", "workspace_id", "meeting_id", "created_at", "id"),
)
chat_citations = Table(
    "chat_citations",
    metadata,
    identity(),
    Column("workspace_id", String(36), nullable=False),
    Column("meeting_id", String(36), nullable=False),
    Column("message_id", String(36), nullable=False),
    Column("segment_id", String(36)),
    Column("original_segment_public_id", String(36), nullable=False),
    Column("source_revision", Integer, nullable=False),
    Column("timestamp_ms", Integer, nullable=False),
    segment_fk(),
    ForeignKeyConstraint(
        ["workspace_id", "meeting_id", "message_id"],
        ["chat_messages.workspace_id", "chat_messages.meeting_id", "chat_messages.id"],
        ondelete="CASCADE",
    ),
    UniqueConstraint("message_id", "original_segment_public_id"),
)
activity_events = Table(
    "activity_events",
    metadata,
    identity(),
    Column("workspace_id", ForeignKey("workspaces.id", ondelete="CASCADE"), nullable=False),
    Column("actor_id", String(36), nullable=False),
    Column("meeting_id", String(36)),
    Column("kind", String(50), nullable=False),
    Column("text", String(250), nullable=False),
    Column("is_read", Boolean, nullable=False, default=False),
    version(),
    *timestamps(),
    ForeignKeyConstraint(
        ["workspace_id", "actor_id"],
        ["workspace_memberships.workspace_id", "workspace_memberships.user_id"],
    ),
    ForeignKeyConstraint(["workspace_id", "meeting_id"], ["meetings.workspace_id", "meetings.id"]),
    Index("ix_activity_chronological", "workspace_id", "created_at", "id"),
)
idempotency_records = Table(
    "idempotency_records",
    metadata,
    Column("workspace_id", ForeignKey("workspaces.id", ondelete="CASCADE"), primary_key=True),
    Column("key", String(100), primary_key=True),
    Column("endpoint", String(200), primary_key=True),
    Column("body_hash", String(64), nullable=False),
    Column("state", String, nullable=False),
    Column("response_json", Text),
    Column("status_code", Integer),
    Column("expires_at", String, nullable=False),
    *timestamps(),
    CheckConstraint("state IN ('pending','complete','failed')", name="state"),
)
search_documents = Table(
    "search_documents",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("public_id", String(36), nullable=False, unique=True),
    Column("workspace_id", String(36), nullable=False),
    Column("meeting_id", String(36), nullable=False),
    Column("segment_id", String(36)),
    Column("kind", String, nullable=False),
    Column("text", Text, nullable=False),
    meeting_fk(),
    segment_fk(),
    CheckConstraint("kind IN ('title','transcript')", name="kind"),
    Index("ix_search_scope", "workspace_id", "meeting_id"),
)
