from sqlalchemy import CheckConstraint, Column, Integer, String, Table, Text

from app.models.common import (
    author_fk,
    identity,
    meeting_fk,
    metadata,
    segment_fk,
    timestamps,
    version,
)

comments = Table(
    "comments",
    metadata,
    identity(),
    Column("workspace_id", String(36), nullable=False),
    Column("meeting_id", String(36), nullable=False),
    Column("segment_id", String(36), nullable=False),
    Column("author_id", String(36), nullable=False),
    Column("body", Text, nullable=False),
    version(),
    *timestamps(),
    meeting_fk(),
    segment_fk(),
    author_fk(),
    CheckConstraint("length(body) BETWEEN 1 AND 4000", name="body"),
)
highlights = Table(
    "highlights",
    metadata,
    identity(),
    Column("workspace_id", String(36), nullable=False),
    Column("meeting_id", String(36), nullable=False),
    Column("segment_id", String(36), nullable=False),
    Column("author_id", String(36), nullable=False),
    Column("start_offset", Integer, nullable=False),
    Column("end_offset", Integer, nullable=False),
    Column("selected_text", Text, nullable=False),
    Column("note", String(4000), nullable=False, default=""),
    Column("color", String, nullable=False, default="amber"),
    version(),
    *timestamps(),
    meeting_fk(),
    segment_fk(),
    author_fk(),
    CheckConstraint("start_offset >= 0 AND end_offset > start_offset", name="range"),
    CheckConstraint("color IN ('purple','blue','green','amber','rose')", name="color"),
)
soundbites = Table(
    "soundbites",
    metadata,
    identity(),
    Column("workspace_id", String(36), nullable=False),
    Column("meeting_id", String(36), nullable=False),
    Column("author_id", String(36), nullable=False),
    Column("title", String(200), nullable=False),
    Column("start_ms", Integer, nullable=False),
    Column("end_ms", Integer, nullable=False),
    version(),
    *timestamps(),
    meeting_fk(),
    author_fk(),
    CheckConstraint("start_ms >= 0 AND end_ms > start_ms", name="times"),
)
