from sqlalchemy import (
    Boolean,
    CheckConstraint,
    Column,
    ForeignKeyConstraint,
    Index,
    Integer,
    String,
    Table,
    Text,
    UniqueConstraint,
)

from app.models.common import identity, meeting_fk, metadata, segment_fk, timestamps, version

summaries = Table(
    "meeting_summaries",
    metadata,
    identity(),
    Column("workspace_id", String(36), nullable=False),
    Column("meeting_id", String(36), nullable=False, unique=True),
    Column("overview", Text, nullable=False),
    Column("notes", Text, nullable=False, default=""),
    Column("provider", String, nullable=False),
    Column("model", String(120)),
    Column("source_revision", Integer, nullable=False),
    Column("generated_at", String, nullable=False),
    version(),
    *timestamps(),
    meeting_fk(),
    UniqueConstraint("workspace_id", "meeting_id", "id"),
    CheckConstraint("provider IN ('extractive','openai')", name="provider"),
    CheckConstraint("length(notes) <= 20000", name="notes"),
)
summary_points = Table(
    "summary_points",
    metadata,
    identity(),
    Column("workspace_id", String(36), nullable=False),
    Column("meeting_id", String(36), nullable=False),
    Column("summary_id", String(36), nullable=False),
    Column("kind", String, nullable=False),
    Column("text", Text, nullable=False),
    Column("position", Integer, nullable=False),
    Column("source_segment_id", String(36)),
    ForeignKeyConstraint(
        ["workspace_id", "meeting_id", "summary_id"],
        ["meeting_summaries.workspace_id", "meeting_summaries.meeting_id", "meeting_summaries.id"],
        ondelete="CASCADE",
    ),
    segment_fk("source_segment_id"),
    CheckConstraint("kind IN ('key_point','decision')", name="kind"),
)
chapters = Table(
    "chapters",
    metadata,
    identity(),
    Column("workspace_id", String(36), nullable=False),
    Column("meeting_id", String(36), nullable=False),
    Column("title", String(200), nullable=False),
    Column("description", Text, nullable=False),
    Column("start_ms", Integer, nullable=False),
    Column("end_ms", Integer, nullable=False),
    Column("position", Integer, nullable=False),
    Column("source_revision", Integer, nullable=False),
    meeting_fk(),
    CheckConstraint("start_ms >= 0 AND end_ms > start_ms", name="times"),
)
action_items = Table(
    "action_items",
    metadata,
    identity(),
    Column("workspace_id", String(36), nullable=False),
    Column("meeting_id", String(36), nullable=False),
    Column("text", Text, nullable=False),
    Column("assignee_participant_id", String(36)),
    Column("due_date", String(10)),
    Column("status", String, nullable=False, default="open"),
    Column("completed_at", String),
    Column("source_segment_id", String(36)),
    Column("origin", String, nullable=False, default="manual"),
    Column("source_revision", Integer),
    Column("user_edited", Boolean, nullable=False, default=False),
    version(),
    *timestamps(),
    meeting_fk(),
    segment_fk("source_segment_id"),
    ForeignKeyConstraint(
        ["workspace_id", "meeting_id", "assignee_participant_id"],
        [
            "meeting_participants.workspace_id",
            "meeting_participants.meeting_id",
            "meeting_participants.participant_id",
        ],
    ),
    CheckConstraint("length(text) BETWEEN 1 AND 2000", name="text"),
    CheckConstraint("origin IN ('manual','extracted')", name="origin"),
    CheckConstraint(
        "(status = 'open' AND completed_at IS NULL) OR (status = 'complete"
        "d' AND completed_at IS NOT NULL)",
        name="completion",
    ),
    Index("ix_tasks_workspace", "workspace_id", "status", "due_date"),
)
