"""create scoped meeting storage

Revision ID: af0016f7371b
Revises:
Create Date: 2026-10-06 19:26:46.469442

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "af0016f7371b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_table(
        "workspaces",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspaces")),
    )
    op.create_table(
        "idempotency_records",
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("endpoint", sa.String(length=200), nullable=False),
        sa.Column("body_hash", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("response_json", sa.Text(), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("expires_at", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.CheckConstraint(
            "state IN ('pending','complete','failed')", name=op.f("ck_idempotency_records_state")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_idempotency_records_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "workspace_id", "key", "endpoint", name=op.f("pk_idempotency_records")
        ),
    )
    op.create_table(
        "participants",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("normalized_email", sa.String(length=254), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_participants_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_participants")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_participants_workspace_id")),
        sa.UniqueConstraint(
            "workspace_id", "normalized_email", name=op.f("uq_participants_workspace_id")
        ),
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("normalized_name", sa.String(length=60), nullable=False),
        sa.Column("color", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.CheckConstraint(
            "color IN ('purple','blue','green','amber','rose','gray')", name=op.f("ck_tags_color")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_tags_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tags")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_tags_workspace_id")),
        sa.UniqueConstraint("workspace_id", "normalized_name", name=op.f("uq_tags_workspace_id")),
    )
    op.create_table(
        "workspace_memberships",
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.CheckConstraint("role IN ('owner')", name=op.f("ck_workspace_memberships_role")),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_workspace_memberships_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_workspace_memberships_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("workspace_id", "user_id", name=op.f("pk_workspace_memberships")),
    )
    op.create_table(
        "demo_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("expires_at", sa.String(), nullable=False),
        sa.Column("last_seen_at", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id", "user_id"],
            ["workspace_memberships.workspace_id", "workspace_memberships.user_id"],
            name=op.f("fk_demo_sessions_workspace_id_workspace_memberships"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_demo_sessions")),
        sa.UniqueConstraint("workspace_id", name=op.f("uq_demo_sessions_workspace_id")),
    )
    op.create_table(
        "meetings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("created_by_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("occurred_at", sa.String(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("media_mode", sa.String(), nullable=False),
        sa.Column("sample_media_key", sa.String(), nullable=True),
        sa.Column("estimated_timing", sa.Integer(), nullable=False),
        sa.Column("transcript_revision", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.CheckConstraint("media_mode IN ('simulated','sample')", name=op.f("ck_meetings_media")),
        sa.CheckConstraint(
            "sample_media_key IS NULL OR sample_media_key = 'welcome'",
            name=op.f("ck_meetings_sample_key"),
        ),
        sa.CheckConstraint(
            "source IN ('seeded','pasted','uploaded','manual')", name=op.f("ck_meetings_source")
        ),
        sa.CheckConstraint(
            "duration_ms BETWEEN 1000 AND 21600000", name=op.f("ck_meetings_duration")
        ),
        sa.CheckConstraint("length(title) BETWEEN 1 AND 200", name=op.f("ck_meetings_title")),
        sa.CheckConstraint(
            "transcript_revision >= 1 AND version >= 1", name=op.f("ck_meetings_revision")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "created_by_id"],
            ["workspace_memberships.workspace_id", "workspace_memberships.user_id"],
            name=op.f("fk_meetings_workspace_id_workspace_memberships"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_meetings_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meetings")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_meetings_workspace_id")),
    )
    with op.batch_alter_table("meetings", schema=None) as batch_op:
        batch_op.create_index(
            "ix_meetings_recent", ["workspace_id", "occurred_at", "id"], unique=False
        )

    op.create_table(
        "user_preferences",
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("theme", sa.String(), nullable=False),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("player_speed", sa.Float(), nullable=False),
        sa.Column("reduced_motion", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.CheckConstraint(
            "theme IN ('light','dark','system')", name=op.f("ck_user_preferences_theme")
        ),
        sa.CheckConstraint(
            "player_speed IN (0.5,0.75,1,1.25,1.5,2)", name=op.f("ck_user_preferences_speed")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "user_id"],
            ["workspace_memberships.workspace_id", "workspace_memberships.user_id"],
            name=op.f("fk_user_preferences_workspace_id_workspace_memberships"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("workspace_id", "user_id", name=op.f("pk_user_preferences")),
    )
    op.create_table(
        "activity_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("actor_id", sa.String(length=36), nullable=False),
        sa.Column("meeting_id", sa.String(length=36), nullable=True),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("text", sa.String(length=250), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id", "actor_id"],
            ["workspace_memberships.workspace_id", "workspace_memberships.user_id"],
            name=op.f("fk_activity_events_workspace_id_workspace_memberships"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "meeting_id"],
            ["meetings.workspace_id", "meetings.id"],
            name=op.f("fk_activity_events_workspace_id_meetings"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_activity_events_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activity_events")),
    )
    with op.batch_alter_table("activity_events", schema=None) as batch_op:
        batch_op.create_index(
            "ix_activity_chronological", ["workspace_id", "created_at", "id"], unique=False
        )

    op.create_table(
        "chapters",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("meeting_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("start_ms", sa.Integer(), nullable=False),
        sa.Column("end_ms", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("source_revision", sa.Integer(), nullable=False),
        sa.CheckConstraint("start_ms >= 0 AND end_ms > start_ms", name=op.f("ck_chapters_times")),
        sa.ForeignKeyConstraint(
            ["workspace_id", "meeting_id"],
            ["meetings.workspace_id", "meetings.id"],
            name=op.f("fk_chapters_workspace_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chapters")),
    )
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("meeting_id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("provider", sa.String(), nullable=True),
        sa.Column("model", sa.String(length=120), nullable=True),
        sa.Column("source_revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.CheckConstraint("role IN ('user','assistant')", name=op.f("ck_chat_messages_role")),
        sa.ForeignKeyConstraint(
            ["workspace_id", "meeting_id"],
            ["meetings.workspace_id", "meetings.id"],
            name=op.f("fk_chat_messages_workspace_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_messages")),
        sa.UniqueConstraint(
            "workspace_id", "meeting_id", "id", name=op.f("uq_chat_messages_workspace_id")
        ),
    )
    with op.batch_alter_table("chat_messages", schema=None) as batch_op:
        batch_op.create_index(
            "ix_chat_chronological",
            ["workspace_id", "meeting_id", "created_at", "id"],
            unique=False,
        )

    op.create_table(
        "meeting_participants",
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("meeting_id", sa.String(length=36), nullable=False),
        sa.Column("participant_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("joined_at", sa.String(), nullable=True),
        sa.CheckConstraint(
            "role IN ('host','attendee')", name=op.f("ck_meeting_participants_role")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "meeting_id"],
            ["meetings.workspace_id", "meetings.id"],
            name=op.f("fk_meeting_participants_workspace_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "participant_id"],
            ["participants.workspace_id", "participants.id"],
            name=op.f("fk_meeting_participants_workspace_id_participants"),
        ),
        sa.PrimaryKeyConstraint(
            "meeting_id", "participant_id", name=op.f("pk_meeting_participants")
        ),
        sa.UniqueConstraint(
            "workspace_id",
            "meeting_id",
            "participant_id",
            name=op.f("uq_meeting_participants_workspace_id"),
        ),
    )
    with op.batch_alter_table("meeting_participants", schema=None) as batch_op:
        batch_op.create_index(
            "ix_attendees_participant",
            ["workspace_id", "participant_id", "meeting_id"],
            unique=False,
        )

    op.create_table(
        "meeting_speakers",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("meeting_id", sa.String(length=36), nullable=False),
        sa.Column("participant_id", sa.String(length=36), nullable=True),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("stable_color_key", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "stable_color_key BETWEEN 0 AND 7 AND position >= 0",
            name=op.f("ck_meeting_speakers_position"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "meeting_id"],
            ["meetings.workspace_id", "meetings.id"],
            name=op.f("fk_meeting_speakers_workspace_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "participant_id"],
            ["participants.workspace_id", "participants.id"],
            name=op.f("fk_meeting_speakers_workspace_id_participants"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meeting_speakers")),
        sa.UniqueConstraint(
            "workspace_id", "meeting_id", "id", name=op.f("uq_meeting_speakers_workspace_id")
        ),
    )
    op.create_table(
        "meeting_summaries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("meeting_id", sa.String(length=36), nullable=False),
        sa.Column("overview", sa.Text(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=True),
        sa.Column("source_revision", sa.Integer(), nullable=False),
        sa.Column("generated_at", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.CheckConstraint(
            "provider IN ('extractive','openai')", name=op.f("ck_meeting_summaries_provider")
        ),
        sa.CheckConstraint("length(notes) <= 20000", name=op.f("ck_meeting_summaries_notes")),
        sa.ForeignKeyConstraint(
            ["workspace_id", "meeting_id"],
            ["meetings.workspace_id", "meetings.id"],
            name=op.f("fk_meeting_summaries_workspace_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meeting_summaries")),
        sa.UniqueConstraint("meeting_id", name=op.f("uq_meeting_summaries_meeting_id")),
        sa.UniqueConstraint(
            "workspace_id", "meeting_id", "id", name=op.f("uq_meeting_summaries_workspace_id")
        ),
    )
    op.create_table(
        "meeting_tags",
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("meeting_id", sa.String(length=36), nullable=False),
        sa.Column("tag_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id", "meeting_id"],
            ["meetings.workspace_id", "meetings.id"],
            name=op.f("fk_meeting_tags_workspace_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "tag_id"],
            ["tags.workspace_id", "tags.id"],
            name=op.f("fk_meeting_tags_workspace_id_tags"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("meeting_id", "tag_id", name=op.f("pk_meeting_tags")),
    )
    with op.batch_alter_table("meeting_tags", schema=None) as batch_op:
        batch_op.create_index(
            "ix_meeting_tags_tag", ["workspace_id", "tag_id", "meeting_id"], unique=False
        )

    op.create_table(
        "soundbites",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("meeting_id", sa.String(length=36), nullable=False),
        sa.Column("author_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("start_ms", sa.Integer(), nullable=False),
        sa.Column("end_ms", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.CheckConstraint("start_ms >= 0 AND end_ms > start_ms", name=op.f("ck_soundbites_times")),
        sa.ForeignKeyConstraint(
            ["workspace_id", "author_id"],
            ["workspace_memberships.workspace_id", "workspace_memberships.user_id"],
            name=op.f("fk_soundbites_workspace_id_workspace_memberships"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "meeting_id"],
            ["meetings.workspace_id", "meetings.id"],
            name=op.f("fk_soundbites_workspace_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_soundbites")),
    )
    op.create_table(
        "transcript_segments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("meeting_id", sa.String(length=36), nullable=False),
        sa.Column("speaker_id", sa.String(length=36), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("start_ms", sa.Integer(), nullable=False),
        sa.Column("end_ms", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.CheckConstraint(
            "length(text) BETWEEN 1 AND 10000", name=op.f("ck_transcript_segments_text")
        ),
        sa.CheckConstraint(
            "start_ms >= 0 AND end_ms > start_ms AND ordinal >= 0",
            name=op.f("ck_transcript_segments_times"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "meeting_id", "speaker_id"],
            ["meeting_speakers.workspace_id", "meeting_speakers.meeting_id", "meeting_speakers.id"],
            name=op.f("fk_transcript_segments_workspace_id_meeting_speakers"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "meeting_id"],
            ["meetings.workspace_id", "meetings.id"],
            name=op.f("fk_transcript_segments_workspace_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transcript_segments")),
        sa.UniqueConstraint(
            "meeting_id", "ordinal", name=op.f("uq_transcript_segments_meeting_id")
        ),
        sa.UniqueConstraint("public_id", name=op.f("uq_transcript_segments_public_id")),
        sa.UniqueConstraint(
            "workspace_id",
            "meeting_id",
            "public_id",
            name=op.f("uq_transcript_segments_workspace_id"),
        ),
    )
    with op.batch_alter_table("transcript_segments", schema=None) as batch_op:
        batch_op.create_index(
            "ix_segments_timeline", ["meeting_id", "start_ms", "ordinal"], unique=False
        )

    op.create_table(
        "action_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("meeting_id", sa.String(length=36), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("assignee_participant_id", sa.String(length=36), nullable=True),
        sa.Column("due_date", sa.String(length=10), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("completed_at", sa.String(), nullable=True),
        sa.Column("source_segment_id", sa.String(length=36), nullable=True),
        sa.Column("origin", sa.String(), nullable=False),
        sa.Column("source_revision", sa.Integer(), nullable=True),
        sa.Column("user_edited", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.CheckConstraint(
            "(status = 'open' AND completed_at IS NULL) OR (status = 'complete"
            "d' AND completed_at IS NOT NULL)",
            name=op.f("ck_action_items_completion"),
        ),
        sa.CheckConstraint("origin IN ('manual','extracted')", name=op.f("ck_action_items_origin")),
        sa.CheckConstraint("length(text) BETWEEN 1 AND 2000", name=op.f("ck_action_items_text")),
        sa.ForeignKeyConstraint(
            ["workspace_id", "meeting_id", "assignee_participant_id"],
            [
                "meeting_participants.workspace_id",
                "meeting_participants.meeting_id",
                "meeting_participants.participant_id",
            ],
            name=op.f("fk_action_items_workspace_id_meeting_participants"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "meeting_id", "source_segment_id"],
            [
                "transcript_segments.workspace_id",
                "transcript_segments.meeting_id",
                "transcript_segments.public_id",
            ],
            name=op.f("fk_action_items_workspace_id_transcript_segments"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "meeting_id"],
            ["meetings.workspace_id", "meetings.id"],
            name=op.f("fk_action_items_workspace_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_action_items")),
    )
    with op.batch_alter_table("action_items", schema=None) as batch_op:
        batch_op.create_index(
            "ix_tasks_workspace", ["workspace_id", "status", "due_date"], unique=False
        )

    op.create_table(
        "chat_citations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("meeting_id", sa.String(length=36), nullable=False),
        sa.Column("message_id", sa.String(length=36), nullable=False),
        sa.Column("segment_id", sa.String(length=36), nullable=True),
        sa.Column("original_segment_public_id", sa.String(length=36), nullable=False),
        sa.Column("source_revision", sa.Integer(), nullable=False),
        sa.Column("timestamp_ms", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id", "meeting_id", "message_id"],
            ["chat_messages.workspace_id", "chat_messages.meeting_id", "chat_messages.id"],
            name=op.f("fk_chat_citations_workspace_id_chat_messages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "meeting_id", "segment_id"],
            [
                "transcript_segments.workspace_id",
                "transcript_segments.meeting_id",
                "transcript_segments.public_id",
            ],
            name=op.f("fk_chat_citations_workspace_id_transcript_segments"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_citations")),
        sa.UniqueConstraint(
            "message_id", "original_segment_public_id", name=op.f("uq_chat_citations_message_id")
        ),
    )
    op.create_table(
        "comments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("meeting_id", sa.String(length=36), nullable=False),
        sa.Column("segment_id", sa.String(length=36), nullable=False),
        sa.Column("author_id", sa.String(length=36), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.CheckConstraint("length(body) BETWEEN 1 AND 4000", name=op.f("ck_comments_body")),
        sa.ForeignKeyConstraint(
            ["workspace_id", "author_id"],
            ["workspace_memberships.workspace_id", "workspace_memberships.user_id"],
            name=op.f("fk_comments_workspace_id_workspace_memberships"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "meeting_id", "segment_id"],
            [
                "transcript_segments.workspace_id",
                "transcript_segments.meeting_id",
                "transcript_segments.public_id",
            ],
            name=op.f("fk_comments_workspace_id_transcript_segments"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "meeting_id"],
            ["meetings.workspace_id", "meetings.id"],
            name=op.f("fk_comments_workspace_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comments")),
    )
    op.create_table(
        "highlights",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("meeting_id", sa.String(length=36), nullable=False),
        sa.Column("segment_id", sa.String(length=36), nullable=False),
        sa.Column("author_id", sa.String(length=36), nullable=False),
        sa.Column("start_offset", sa.Integer(), nullable=False),
        sa.Column("end_offset", sa.Integer(), nullable=False),
        sa.Column("selected_text", sa.Text(), nullable=False),
        sa.Column("note", sa.String(length=4000), nullable=False),
        sa.Column("color", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.CheckConstraint(
            "color IN ('purple','blue','green','amber','rose')", name=op.f("ck_highlights_color")
        ),
        sa.CheckConstraint(
            "start_offset >= 0 AND end_offset > start_offset", name=op.f("ck_highlights_range")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "author_id"],
            ["workspace_memberships.workspace_id", "workspace_memberships.user_id"],
            name=op.f("fk_highlights_workspace_id_workspace_memberships"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "meeting_id", "segment_id"],
            [
                "transcript_segments.workspace_id",
                "transcript_segments.meeting_id",
                "transcript_segments.public_id",
            ],
            name=op.f("fk_highlights_workspace_id_transcript_segments"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "meeting_id"],
            ["meetings.workspace_id", "meetings.id"],
            name=op.f("fk_highlights_workspace_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_highlights")),
    )
    op.create_table(
        "search_documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("meeting_id", sa.String(length=36), nullable=False),
        sa.Column("segment_id", sa.String(length=36), nullable=True),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.CheckConstraint("kind IN ('title','transcript')", name=op.f("ck_search_documents_kind")),
        sa.ForeignKeyConstraint(
            ["workspace_id", "meeting_id", "segment_id"],
            [
                "transcript_segments.workspace_id",
                "transcript_segments.meeting_id",
                "transcript_segments.public_id",
            ],
            name=op.f("fk_search_documents_workspace_id_transcript_segments"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "meeting_id"],
            ["meetings.workspace_id", "meetings.id"],
            name=op.f("fk_search_documents_workspace_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_documents")),
        sa.UniqueConstraint("public_id", name=op.f("uq_search_documents_public_id")),
    )
    with op.batch_alter_table("search_documents", schema=None) as batch_op:
        batch_op.create_index("ix_search_scope", ["workspace_id", "meeting_id"], unique=False)

    op.create_table(
        "summary_points",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("meeting_id", sa.String(length=36), nullable=False),
        sa.Column("summary_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("source_segment_id", sa.String(length=36), nullable=True),
        sa.CheckConstraint("kind IN ('key_point','decision')", name=op.f("ck_summary_points_kind")),
        sa.ForeignKeyConstraint(
            ["workspace_id", "meeting_id", "source_segment_id"],
            [
                "transcript_segments.workspace_id",
                "transcript_segments.meeting_id",
                "transcript_segments.public_id",
            ],
            name=op.f("fk_summary_points_workspace_id_transcript_segments"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "meeting_id", "summary_id"],
            [
                "meeting_summaries.workspace_id",
                "meeting_summaries.meeting_id",
                "meeting_summaries.id",
            ],
            name=op.f("fk_summary_points_workspace_id_meeting_summaries"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_summary_points")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("summary_points")
    with op.batch_alter_table("search_documents", schema=None) as batch_op:
        batch_op.drop_index("ix_search_scope")

    op.drop_table("search_documents")
    op.drop_table("highlights")
    op.drop_table("comments")
    op.drop_table("chat_citations")
    with op.batch_alter_table("action_items", schema=None) as batch_op:
        batch_op.drop_index("ix_tasks_workspace")

    op.drop_table("action_items")
    with op.batch_alter_table("transcript_segments", schema=None) as batch_op:
        batch_op.drop_index("ix_segments_timeline")

    op.drop_table("transcript_segments")
    op.drop_table("soundbites")
    with op.batch_alter_table("meeting_tags", schema=None) as batch_op:
        batch_op.drop_index("ix_meeting_tags_tag")

    op.drop_table("meeting_tags")
    op.drop_table("meeting_summaries")
    op.drop_table("meeting_speakers")
    with op.batch_alter_table("meeting_participants", schema=None) as batch_op:
        batch_op.drop_index("ix_attendees_participant")

    op.drop_table("meeting_participants")
    with op.batch_alter_table("chat_messages", schema=None) as batch_op:
        batch_op.drop_index("ix_chat_chronological")

    op.drop_table("chat_messages")
    op.drop_table("chapters")
    with op.batch_alter_table("activity_events", schema=None) as batch_op:
        batch_op.drop_index("ix_activity_chronological")

    op.drop_table("activity_events")
    op.drop_table("user_preferences")
    with op.batch_alter_table("meetings", schema=None) as batch_op:
        batch_op.drop_index("ix_meetings_recent")

    op.drop_table("meetings")
    op.drop_table("demo_sessions")
    op.drop_table("workspace_memberships")
    op.drop_table("tags")
    op.drop_table("participants")
    op.drop_table("idempotency_records")
    op.drop_table("workspaces")
    op.drop_table("users")
    # ### end Alembic commands ###
