/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Session Create */
        post: operations["session_create_api_v1_demo_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profile */
        get: operations["profile_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Preferences */
        get: operations["read_preferences_api_v1_me_preferences_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Write Preferences */
        patch: operations["write_preferences_api_v1_me_preferences_patch"];
        trace?: never;
    };
    "/api/v1/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Participants */
        get: operations["list_participants_api_v1_participants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/participants/{participant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit Participant */
        patch: operations["edit_participant_api_v1_participants__participant_id__patch"];
        trace?: never;
    };
    "/api/v1/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tags */
        get: operations["list_tags_api_v1_tags_get"];
        put?: never;
        /** Create Tag */
        post: operations["create_tag_api_v1_tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tags/{tag_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Tag */
        delete: operations["delete_tag_api_v1_tags__tag_id__delete"];
        options?: never;
        head?: never;
        /** Edit Tag */
        patch: operations["edit_tag_api_v1_tags__tag_id__patch"];
        trace?: never;
    };
    "/api/v1/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Activity */
        get: operations["activity_api_v1_activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activity/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark Activity */
        patch: operations["mark_activity_api_v1_activity__event_id__patch"];
        trace?: never;
    };
    "/api/v1/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Meetings */
        get: operations["list_meetings_api_v1_meetings_get"];
        put?: never;
        /** Create */
        post: operations["create_api_v1_meetings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detail */
        get: operations["detail_api_v1_meetings__meeting_id__get"];
        put?: never;
        post?: never;
        /** Remove */
        delete: operations["remove_api_v1_meetings__meeting_id__delete"];
        options?: never;
        head?: never;
        /** Edit */
        patch: operations["edit_api_v1_meetings__meeting_id__patch"];
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Tags */
        put: operations["set_tags_api_v1_meetings__meeting_id__tags_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Attendees */
        put: operations["set_attendees_api_v1_meetings__meeting_id__participants_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}/speakers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Speakers */
        get: operations["list_speakers_api_v1_meetings__meeting_id__speakers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}/speakers/{speaker_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit Speaker */
        patch: operations["edit_speaker_api_v1_meetings__meeting_id__speakers__speaker_id__patch"];
        trace?: never;
    };
    "/api/v1/action-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workspace Tasks */
        get: operations["workspace_tasks_api_v1_action_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}/action-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meeting Tasks */
        get: operations["meeting_tasks_api_v1_meetings__meeting_id__action_items_get"];
        put?: never;
        /** Add Task */
        post: operations["add_task_api_v1_meetings__meeting_id__action_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}/action-items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Task */
        delete: operations["remove_task_api_v1_meetings__meeting_id__action_items__item_id__delete"];
        options?: never;
        head?: never;
        /** Edit Task */
        patch: operations["edit_task_api_v1_meetings__meeting_id__action_items__item_id__patch"];
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Transcript */
        get: operations["transcript_api_v1_meetings__meeting_id__transcript_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Timeline */
        get: operations["timeline_api_v1_meetings__meeting_id__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}/transcript/window": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Window */
        get: operations["window_api_v1_meetings__meeting_id__transcript_window_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}/transcript/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_v1_meetings__meeting_id__transcript_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary */
        get: operations["summary_api_v1_meetings__meeting_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Notes */
        patch: operations["notes_api_v1_meetings__meeting_id__summary_patch"];
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}/chapters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Outline */
        get: operations["outline_api_v1_meetings__meeting_id__chapters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Activity */
        Activity: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Meeting Id */
            meeting_id: string | null;
            /** Kind */
            kind: string;
            /** Text */
            text: string;
            /** Is Read */
            is_read: boolean;
            /** Created At */
            created_at: string;
            /** Version */
            version: number;
        };
        /** ActivityUpdate */
        ActivityUpdate: {
            /** Is Read */
            is_read: boolean;
        };
        /** AttendeesUpdate */
        AttendeesUpdate: {
            /** Participant Ids */
            participant_ids: string[];
            /**
             * Removed Task Action
             * @enum {string}
             */
            removed_task_action: "unassign" | "reassign";
            /** Reassign To */
            reassign_to?: string | null;
        };
        /** Chapter */
        Chapter: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Start Ms */
            start_ms: number;
            /** End Ms */
            end_ms: number;
            /** Source Revision */
            source_revision: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Meeting */
        Meeting: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Occurred At */
            occurred_at: string;
            /** Duration Ms */
            duration_ms: number;
            /**
             * Source
             * @enum {string}
             */
            source: "seeded" | "pasted" | "uploaded" | "manual";
            /** Description */
            description: string | null;
            /**
             * Media Mode
             * @enum {string}
             */
            media_mode: "simulated" | "sample";
            /** Sample Media Key */
            sample_media_key: string | null;
            /** Estimated Timing */
            estimated_timing: boolean;
            /** Transcript Revision */
            transcript_revision: number;
            /** Version */
            version: number;
            /**
             * Participants
             * @default []
             */
            participants: components["schemas"]["Participant"][];
            /**
             * Tags
             * @default []
             */
            tags: components["schemas"]["Tag"][];
        };
        /** MeetingCreate */
        MeetingCreate: {
            /** Title */
            title: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Duration Ms */
            duration_ms: number;
            /**
             * Source
             * @default manual
             * @enum {string}
             */
            source: "pasted" | "manual" | "uploaded";
            /** Participants */
            participants?: components["schemas"]["PersonInput"][];
            /** Segments */
            segments: components["schemas"]["SegmentInput"][];
            /** Tag Ids */
            tag_ids?: string[];
            /**
             * Estimated Timing
             * @default false
             */
            estimated_timing: boolean;
            /**
             * Acknowledge Estimated
             * @default false
             */
            acknowledge_estimated: boolean;
        };
        /** MeetingUpdate */
        MeetingUpdate: {
            /** Title */
            title?: string | null;
            /** Occurred At */
            occurred_at?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Description */
            description?: string | null;
        };
        /** NotesUpdate */
        NotesUpdate: {
            /** Notes */
            notes: string;
        };
        /** Page[Activity] */
        Page_Activity_: {
            /** Items */
            items: components["schemas"]["Activity"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /**
             * Has More
             * @default false
             */
            has_more: boolean;
            /**
             * Applied Filters
             * @default {}
             */
            applied_filters: {
                [key: string]: string | number | null;
            };
        };
        /** Page[Meeting] */
        Page_Meeting_: {
            /** Items */
            items: components["schemas"]["Meeting"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /**
             * Has More
             * @default false
             */
            has_more: boolean;
            /**
             * Applied Filters
             * @default {}
             */
            applied_filters: {
                [key: string]: string | number | null;
            };
        };
        /** Page[Participant] */
        Page_Participant_: {
            /** Items */
            items: components["schemas"]["Participant"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /**
             * Has More
             * @default false
             */
            has_more: boolean;
            /**
             * Applied Filters
             * @default {}
             */
            applied_filters: {
                [key: string]: string | number | null;
            };
        };
        /** Page[Tag] */
        Page_Tag_: {
            /** Items */
            items: components["schemas"]["Tag"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /**
             * Has More
             * @default false
             */
            has_more: boolean;
            /**
             * Applied Filters
             * @default {}
             */
            applied_filters: {
                [key: string]: string | number | null;
            };
        };
        /** Page[Task] */
        Page_Task_: {
            /** Items */
            items: components["schemas"]["Task"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /**
             * Has More
             * @default false
             */
            has_more: boolean;
            /**
             * Applied Filters
             * @default {}
             */
            applied_filters: {
                [key: string]: string | number | null;
            };
        };
        /** Participant */
        Participant: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Display Name */
            display_name: string;
            /** Normalized Email */
            normalized_email: string | null;
            /** Version */
            version: number;
        };
        /** ParticipantUpdate */
        ParticipantUpdate: {
            /** Display Name */
            display_name: string;
        };
        /** PersonInput */
        PersonInput: {
            /** Display Name */
            display_name: string;
            /** Email */
            email?: string | null;
        };
        /** Preferences */
        Preferences: {
            /**
             * Theme
             * @enum {string}
             */
            theme: "light" | "dark" | "system";
            /** Timezone */
            timezone: string;
            /** Player Speed */
            player_speed: number;
            /** Reduced Motion */
            reduced_motion: boolean;
            /** Version */
            version: number;
        };
        /** PreferencesUpdate */
        PreferencesUpdate: {
            /** Theme */
            theme?: ("light" | "dark" | "system") | null;
            /** Timezone */
            timezone?: string | null;
            /** Player Speed */
            player_speed?: number | null;
            /** Reduced Motion */
            reduced_motion?: boolean | null;
        };
        /** Profile */
        Profile: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Display Name */
            display_name: string;
            /** Workspace Name */
            workspace_name: string;
            preferences: components["schemas"]["Preferences"];
            /** Ai Available */
            ai_available: boolean;
        };
        /** Segment */
        Segment: {
            /**
             * Public Id
             * Format: uuid
             */
            public_id: string;
            /**
             * Speaker Id
             * Format: uuid
             */
            speaker_id: string;
            /** Ordinal */
            ordinal: number;
            /** Start Ms */
            start_ms: number;
            /** End Ms */
            end_ms: number;
            /** Text */
            text: string;
            /** Version */
            version: number;
            /** Speaker Name */
            speaker_name: string;
            /** Stable Color Key */
            stable_color_key: number;
        };
        /** SegmentInput */
        SegmentInput: {
            /** Speaker */
            speaker: string;
            /** Start Ms */
            start_ms: number;
            /** End Ms */
            end_ms: number;
            /** Text */
            text: string;
        };
        /** SessionResult */
        SessionResult: {
            /**
             * Ready
             * @default true
             */
            ready: boolean;
        };
        /** Speaker */
        Speaker: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Display Name */
            display_name: string;
            /** Participant Id */
            participant_id: string | null;
            /** Stable Color Key */
            stable_color_key: number;
            /** Version */
            version: number;
        };
        /** SpeakerUpdate */
        SpeakerUpdate: {
            /** Display Name */
            display_name: string;
            /** Participant Id */
            participant_id?: string | null;
        };
        /** Summary */
        Summary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Overview */
            overview: string;
            /** Notes */
            notes: string;
            /** Provider */
            provider: string;
            /** Model */
            model: string | null;
            /** Source Revision */
            source_revision: number;
            /** Generated At */
            generated_at: string;
            /** Version */
            version: number;
            /** Stale */
            stale: boolean;
            /** Points */
            points: components["schemas"]["SummaryPoint"][];
        };
        /** SummaryPoint */
        SummaryPoint: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Text */
            text: string;
            /** Source Segment Id */
            source_segment_id: string | null;
        };
        /** Tag */
        Tag: {
            /** Name */
            name: string;
            /** Color */
            color: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Version */
            version: number;
        };
        /** TagInput */
        TagInput: {
            /** Name */
            name: string;
            /**
             * Color
             * @default purple
             * @enum {string}
             */
            color: "purple" | "blue" | "green" | "amber" | "rose" | "gray";
        };
        /** TagsUpdate */
        TagsUpdate: {
            /** Tag Ids */
            tag_ids: string[];
        };
        /** Task */
        Task: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Meeting Id
             * Format: uuid
             */
            meeting_id: string;
            /** Text */
            text: string;
            /** Assignee Participant Id */
            assignee_participant_id: string | null;
            /** Due Date */
            due_date: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "open" | "completed";
            /** Completed At */
            completed_at: string | null;
            /** Source Segment Id */
            source_segment_id: string | null;
            /**
             * Origin
             * @enum {string}
             */
            origin: "extracted" | "manual";
            /** Source Revision */
            source_revision: number | null;
            /** User Edited */
            user_edited: boolean;
            /** Version */
            version: number;
        };
        /** TaskInput */
        TaskInput: {
            /** Text */
            text: string;
            /** Assignee Participant Id */
            assignee_participant_id?: string | null;
            /** Due Date */
            due_date?: string | null;
        };
        /** TaskUpdate */
        TaskUpdate: {
            /** Text */
            text?: string | null;
            /** Assignee Participant Id */
            assignee_participant_id?: string | null;
            /** Due Date */
            due_date?: string | null;
            /** Status */
            status?: ("open" | "completed") | null;
        };
        /** TimelineEntry */
        TimelineEntry: {
            /**
             * Public Id
             * Format: uuid
             */
            public_id: string;
            /** Ordinal */
            ordinal: number;
            /** Start Ms */
            start_ms: number;
            /** End Ms */
            end_ms: number;
        };
        /** Transcript */
        Transcript: {
            /** Items */
            items: components["schemas"]["Segment"][];
            /** Next Cursor */
            next_cursor: number | null;
            /** Has More */
            has_more: boolean;
            /** Revision */
            revision: number;
            /** Offset */
            offset: number;
        };
        /** TranscriptHit */
        TranscriptHit: {
            /**
             * Segment Id
             * Format: uuid
             */
            segment_id: string;
            /** Timestamp Ms */
            timestamp_ms: number;
            /** Speaker Name */
            speaker_name: string;
            /** Snippet */
            snippet: string;
            /** Ranges */
            ranges: [
                number,
                number
            ][];
        };
        /** TranscriptSearch */
        TranscriptSearch: {
            /** Items */
            items: components["schemas"]["TranscriptHit"][];
            /** Total */
            total: number;
            /** Next Cursor */
            next_cursor: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    session_create_api_v1_demo_session_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-demo-session"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    profile_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: {
                "x-demo-session"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_preferences_api_v1_me_preferences_get: {
        parameters: {
            query?: never;
            header?: {
                "x-demo-session"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Preferences"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    write_preferences_api_v1_me_preferences_patch: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
                "x-demo-session"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Preferences"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_participants_api_v1_participants_get: {
        parameters: {
            query?: {
                q?: string;
                limit?: number;
            };
            header?: {
                "x-demo-session"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Participant_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_participant_api_v1_participants__participant_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
                "x-demo-session"?: string | null;
                authorization?: string | null;
            };
            path: {
                participant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParticipantUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Participant"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tags_api_v1_tags_get: {
        parameters: {
            query?: never;
            header?: {
                "x-demo-session"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Tag_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_tag_api_v1_tags_post: {
        parameters: {
            query?: never;
            header?: {
                "x-demo-session"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_tag_api_v1_tags__tag_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
                "x-demo-session"?: string | null;
                authorization?: string | null;
            };
            path: {
                tag_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_tag_api_v1_tags__tag_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
                "x-demo-session"?: string | null;
                authorization?: string | null;
            };
            path: {
                tag_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activity_api_v1_activity_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                "x-demo-session"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Activity_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_activity_api_v1_activity__event_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
                "x-demo-session"?: string | null;
                authorization?: string | null;
            };
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivityUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_meetings_api_v1_meetings_get: {
        parameters: {
            query?: {
                q?: string;
                participant?: string | null;
                tag?: string | null;
                after?: string | null;
                before?: string | null;
                minimum?: number | null;
                maximum?: number | null;
                source?: ("seeded" | "pasted" | "uploaded" | "manual") | null;
                sort?: "recent" | "oldest" | "title";
                limit?: number;
                cursor?: string | null;
            };
            header?: {
                "x-demo-session"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Meeting_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_api_v1_meetings_post: {
        parameters: {
            query?: never;
            header: {
                "idempotency-key": string;
                "x-demo-session"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeetingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meeting"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detail_api_v1_meetings__meeting_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-demo-session"?: string | null;
                authorization?: string | null;
            };
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meeting"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_api_v1_meetings__meeting_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
                "x-demo-session"?: string | null;
                authorization?: string | null;
            };
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_api_v1_meetings__meeting_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
                "x-demo-session"?: string | null;
                authorization?: string | null;
            };
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeetingUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meeting"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_tags_api_v1_meetings__meeting_id__tags_put: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
                "x-demo-session"?: string | null;
                authorization?: string | null;
            };
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meeting"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_attendees_api_v1_meetings__meeting_id__participants_put: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
                "x-demo-session"?: string | null;
                authorization?: string | null;
            };
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttendeesUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meeting"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_speakers_api_v1_meetings__meeting_id__speakers_get: {
        parameters: {
            query?: never;
            header?: {
                "x-demo-session"?: string | null;
                authorization?: string | null;
            };
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Speaker"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_speaker_api_v1_meetings__meeting_id__speakers__speaker_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
                "x-demo-session"?: string | null;
                authorization?: string | null;
            };
            path: {
                meeting_id: string;
                speaker_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpeakerUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Speaker"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workspace_tasks_api_v1_action_items_get: {
        parameters: {
            query?: {
                status?: ("open" | "completed") | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: {
                "x-demo-session"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Task_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    meeting_tasks_api_v1_meetings__meeting_id__action_items_get: {
        parameters: {
            query?: never;
            header?: {
                "x-demo-session"?: string | null;
                authorization?: string | null;
            };
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Task_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_task_api_v1_meetings__meeting_id__action_items_post: {
        parameters: {
            query?: never;
            header?: {
                "x-demo-session"?: string | null;
                authorization?: string | null;
            };
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_task_api_v1_meetings__meeting_id__action_items__item_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
                "x-demo-session"?: string | null;
                authorization?: string | null;
            };
            path: {
                meeting_id: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_task_api_v1_meetings__meeting_id__action_items__item_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
                "x-demo-session"?: string | null;
                authorization?: string | null;
            };
            path: {
                meeting_id: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transcript_api_v1_meetings__meeting_id__transcript_get: {
        parameters: {
            query?: {
                cursor?: number;
                limit?: number;
                speaker?: string | null;
            };
            header?: {
                "x-demo-session"?: string | null;
                authorization?: string | null;
            };
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transcript"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    timeline_api_v1_meetings__meeting_id__timeline_get: {
        parameters: {
            query?: never;
            header?: {
                "x-demo-session"?: string | null;
                authorization?: string | null;
            };
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    window_api_v1_meetings__meeting_id__transcript_window_get: {
        parameters: {
            query?: {
                at_ms?: number;
                segment_id?: string | null;
            };
            header?: {
                "x-demo-session"?: string | null;
                authorization?: string | null;
            };
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transcript"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_v1_meetings__meeting_id__transcript_search_get: {
        parameters: {
            query: {
                q: string;
                speaker?: string | null;
                cursor?: number;
            };
            header?: {
                "x-demo-session"?: string | null;
                authorization?: string | null;
            };
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptSearch"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_api_v1_meetings__meeting_id__summary_get: {
        parameters: {
            query?: never;
            header?: {
                "x-demo-session"?: string | null;
                authorization?: string | null;
            };
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Summary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    notes_api_v1_meetings__meeting_id__summary_patch: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
                "x-demo-session"?: string | null;
                authorization?: string | null;
            };
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotesUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Summary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    outline_api_v1_meetings__meeting_id__chapters_get: {
        parameters: {
            query?: never;
            header?: {
                "x-demo-session"?: string | null;
                authorization?: string | null;
            };
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chapter"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
