import type { components } from "./contracts";
export type Meeting = components["schemas"]["Meeting"];
export type Profile = components["schemas"]["Profile"];
export type Preferences = components["schemas"]["Preferences"];
export type Participant = components["schemas"]["Participant"];
export type Tag = components["schemas"]["Tag"];
export type Task = components["schemas"]["Task"];
export type Activity = components["schemas"]["Activity"];
export type Page<T> = Omit<components["schemas"]["Page_Meeting_"], "items"> & {
  items: T[];
};
export type Segment = components["schemas"]["Segment"];
export type Transcript = components["schemas"]["Transcript"];
export type TimelineEntry = components["schemas"]["TimelineEntry"];
export type TranscriptSearch = components["schemas"]["TranscriptSearch"];
export type Summary = components["schemas"]["Summary"];
export type Chapter = components["schemas"]["Chapter"];
export type Speaker = components["schemas"]["Speaker"];
export type ImportPreview = components["schemas"]["ImportPreview"];
export type SegmentInput = components["schemas"]["SegmentInput"];
export type SegmentImpact = components["schemas"]["SegmentImpact"];
